name: github_repos
version: 0.0.1
description: A sample command-line application.
#author: filiph <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  csv: ^3.1.1
  http: ^0.11.3+9

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
